name: Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Desired tag'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.event.inputs.release }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Sync strategies
      run: |
        for file in `ls clusterBuildStrategy/**/*.yaml`
        do 
          cat $file >> release-strategies.yaml
        done
